apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: deployment
  spec:
    replicas: 2
    selector:
      matchLabels:
        identifier: container
    template:
      metadata:
        annotations:
          build_number: "20240125.34"
        labels:
          identifier: container
      spec:
        containers:
        - env:
          - name: ASPNETCORE_URLS
            value: http://+:5000
          image: docker.io/example-organization/aspnet-razor:b762df60
          imagePullPolicy: Always
          name: container
          ports:
          - containerPort: 5000
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
          - mountPath: /app/appsettings.json
            name: appsettings-volume
            readOnly: true
            subPath: appsettings.json
        serviceAccountName: azure-devops
        volumes:
        - configMap:
            name: appsettings-configmap
          name: appsettings-volume
- apiVersion: v1
  kind: Service
  metadata:
    name: service
  spec:
    ports:
    - port: 5000
      targetPort: 5000
    selector:
      identifier: container
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
    labels:
      zone: internal
    name: route
  spec:
    host: aspnet-razor.example.org
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: service
kind: List
metadata: {}
